<div class="grid-x grid padding-x">
<?php include 'addNew.phtml';?>
    <?php foreach ($users as $users) : ?>
        <div class="large-3 medium-4 cell">
            <div class = "callout" style="text-align:center; min-height: 220px;">
                 <h1 style="font-size: 1.5rem;">
                 <?=$users->name?> <?=$users->surname?></h1>
                 <hr />
                 <?=$users->email?>
                 <hr />
                 <a href="<?= App::config('url') ?>users/change?id=<? $users->id ?>">
                    <i title="Change &quot;<?= $users->name ?>&quot;"  
                         class="fas fa-2x fa-edit"></i>
                </a>   
                <?php if ($users->wishlists === 0) : ?>
                    <a onclick="return confirm('Are you sure you want to delete <?= $users->name ?>?');" style="margin-left: 20px;" href="<?= App::config('url') ?>users/delete/<?=$users->id?>">
                        <i style="color: red" title="Delete <?= $users->name ?>"
                             class="fas fa-2x fa-trash"></i>
                    </a>  
                <?php else:?>
                    <i style="margin-left: 20px;color: gray" 
                    title="Cannot delete  <?= $users->name ?> because there are wishlists" 
                            class="fas fa-2x fa-trash"></i>
                <?php endif;?>
            </div>
            
        </div>
    <?php endforeach; ?>
    <?php include 'addNew.phtml';?>
</div>