<form action="<?=App::config('url')?>grupa/promjeni" method="post">

<div class="grid-x grid-padding-x">
    <div class="cell large-6">
   
        <fieldset>
            <legend>Promjena postojeće grupe</legend>


            <label>
                Naziv
                <input type="text" name="naziv" value="<?=$e->naziv?>" />
            </label>

            <label>
                Smjer
                <select name="smjer">
                    <?php foreach($smjerovi as $smjer): ?>
                        <option 
                        <?php if($smjer->sifra==$e->smjer){
                            echo 'selected="selected"';
                        } ?>
                        value="<?=$smjer->sifra?>"><?=$smjer->naziv?></option>
                    <?php endforeach;?>
                </select>
            </label>

            <div class="warning callout">
         
                    <input type="text" id="uvjetPredavac" placeholder="Traži predavača">

                Odabrani predavač: <p id="odabraniPredavac"><?=$labelaPredavaca; ?></p>
            </div>
            

            <label>
                Datum početka
                <input type="date" name="datumpocetka" value="<?php 
                if($e->datumpocetka==null){
                    echo '';
                }else{
                    echo date('Y-m-d',strtotime($e->datumpocetka));
                }
                ?>" lang="hr-HR">
                    </label>
        

            <input type="hidden" name="sifra" value="<?=$e->sifra?>">
            <input type="hidden" id="predavac" name="predavac" value="<?=$e->predavac?>">

            
            <?=$poruka?>

        </fieldset>
      
    </div>
    <div class="cell large-6">
    <input type="text" id="uvjet" placeholder="Traži polaznika">
        <div style="overflow: auto; max-height: 400px; margin-bottom: 20px;">

               
                <table>
                <thead>
                    <tr>
                        <th>Polaznik</th>
                        <th>Akcija</th>
                    </tr>
                </thead>
                <tbody id="polaznici">
                    <?php foreach($e->polaznici as $p): ?>
                        <tr>
                            <td><?=$p->ime?> <?=$p->prezime?></td>
                            <td>
                            
                                <a onclick="return confirm('Sigurno obrisati?');" 
                                id="b_<?=$p->sifra?>"
                                class="brisiPolaznika"
                                href="#">
                                    <i style="color: red" title="Obriši" 
                                        class="fas fa-2x fa-trash"></i>
                                </a>  
                        
                            
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="grid-x grid-padding-x">
    <div class="large-4 cell">
        <a  class="alert button expanded" 
        href="<?=App::config('url')?>grupa/odustani/<?=$e->sifra?>">Odustani</a>
    </div>
    <div class="large-8 cell">
        <input type="submit" class="success button expanded" value="Promjeni">
    </div>
</div>

</form>