<form action="<?= App::config('url') ?>developers/addNew" method="post">

    <fieldset>
        <legend>Add new Developer</legend>


        <label>
            Name
            <input type="text" name="Name" />
        </label>

        <label>
            Country
            <input type="text" name="Country" />
        </label>

        <label>
            Website
            <input type="text" name="Website" />
        </label>

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>developers/index">Cancel</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Add new">
            </div>
        </div>

    </fieldset>
</form>